[program:mod-harvest-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/raptorpanel_dev/artisan queue:work --queue=mod-harvest --sleep=1 --tries=3 --timeout=300 --memory=512
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/raptorpanel_dev/storage/logs/mod-harvest-worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600

[program:mod-harvest-worker-backup]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/raptorpanel_dev/artisan queue:work --queue=mod-harvest --sleep=3 --tries=3 --timeout=300 --memory=512
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/raptorpanel_dev/storage/logs/mod-harvest-worker-backup.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stopwaitsecs=3600